### ISSUE TITLE
Formatting problem in DownloadException obscures error

### ISSUE THREAD

**Issue by neilmb** [seomoz/s3po#19]
I saw the following traceback from a custos qless job:

``` python
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/qless/job.py", line 147, in process
    method(self)
  File "/usr/local/lib/python2.7/dist-packages/custos-0.0.2-py2.7.egg/custos/jobs.py", line 413, in compute
    crawlset = MetricsJob.download(job)
  File "/usr/local/lib/python2.7/dist-packages/custos-0.0.2-py2.7.egg/custos/jobs.py", line 369, in download
    swift_conn.download_file(data_bucket, url_key, urls_file)
  File "/usr/local/lib/python2.7/dist-packages/s3po/connection.py", line 79, in download_file
    return self.download(bucket, key, fout, headers, retries)
  File "/usr/local/lib/python2.7/dist-packages/s3po/connection.py", line 69, in download
    return self.backend.download(bucket, key, obj, retries, headers)
  File "/usr/local/lib/python2.7/dist-packages/s3po/backends/swift.py", line 50, in download
    func()
  File "/usr/local/lib/python2.7/dist-packages/s3po/util.py", line 52, in new_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/s3po/backends/swift.py", line 44, in func
    fobj.count, length))
TypeError: %d format: a number is required, not unicode
```

The problem is that the log statement tries to format the content length header with `%i` which doesn't force the conversion to `int` that appears on the previous line.

**Comment by neilmb** [comment]
This is fixed.
